### ISSUE TITLE
Crash in uv__io_poll

### ISSUE THREAD

**Issue by mspanc** [joyent/libuv#1204]
Today I got crash on 

```
../deps/uv/src/unix/linux-core.c:146: uv__io_poll: Assertion `w->fd >= 0' failed
```

Unfortunately I wasn't able to catch backtrace.

I triggered this by using node-dbus@0.1.3.

node v0.10.25, ubuntu 14.04 beta1

**Comment by saghul** [comment]
Can you reproduce it? If so, can you provide a minimal test case?

**Comment by mspanc** [comment]
Not yet. I work extensively on certain project and I permanently enabled core dumps so if it will happen again I will provide a backtrace.

If it's a hint, it happened most probably in a callback function that is triggered by dbus bindings after a method call.

**Comment by saghul** [comment]
I haven't looked at node-dbus, but I've seen similar crashes if multiple `uv_poll_t` handles are used for a given fd.

**Comment by mspanc** [comment]
I have caught backtrace:

```
#0  0x00007f9e27fcdf79 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f9e27fd1388 in __GI_abort () at abort.c:89
#2  0x00007f9e27fc6e36 in __assert_fail_base (fmt=0x7f9e281184b8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x472ff6 "wrap->handle__ == __null", file=file@entry=0x472fe0 "../src/handle_wrap.cc", line=line@entry=145, 
    function=function@entry=0x473080 "static void node::HandleWrap::OnClose(uv_handle_t*)") at assert.c:92
#3  0x00007f9e27fc6ee2 in __GI___assert_fail (assertion=0x472ff6 "wrap->handle__ == __null", file=0x472fe0 "../src/handle_wrap.cc", line=145, function=0x473080 "static void node::HandleWrap::OnClose(uv_handle_t*)") at assert.c:101
#4  0x0000000000421860 in node::HandleWrap::OnClose(uv_handle_s*) ()
#5  0x000000000046403f in uv_run ()
#6  0x0000000000426e05 in node::Start(int, char**) ()
#7  0x00007f9e27fb8ec5 in __libc_start_main (main=0x41c810 <main>, argc=2, argv=0x7fff78ac8228, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff78ac8218) at libc-start.c:285
#8  0x000000000041caf0 in _start ()
```

This time the error was

```
node: ../src/handle_wrap.cc:145: static void node::HandleWrap::OnClose(uv_handle_t*): Assertion `wrap->handle__ == __null' failed.
```

**Comment by saghul** [comment]
Ping? That last backtrace is an assertion blowing up on Node, not libuv.

**Comment by mspanc** [comment]
I have switched to Ruby, I am unable to debug this any more.

**Comment by saghul** [comment]
No worries. I'll close this then, if someone ever runs into it again we can reopen it.
