### ISSUE TITLE
uv_strerror woes

### ISSUE THREAD

**Issue by piscisaureus** [joyent/libuv#187]
From the nodejs mailing list. Probably due to setting `loop->last_err.errno` but leaving `loop->last_err._sys_errno` alone.

```
Running 0.5.6 on Windows XP 64 getting the following error:

fs.js:222
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: ENOENT, The operation completed successfully.
 'C:\Documents and Settings\Administrator\My Documents\Dropbox\pmmvc
\libs\request.js'
    at Object.openSync (fs.js:222:18)
    at Object.readFileSync (fs.js:113:15)
    at Server.<anonymous> (C:\Documents and Settings\Administrator\My
Documents\Dropbox\pmmvc\index.js:67:13)
    at Server.emit (events.js:70:17)
    at HTTPParser.onIncoming (http2.js:1451:12)
    at HTTPParser.onHeadersComplete (http2.js:108:31)
    at Socket.ondata (http2.js:1347:22)
    at TCP.onread (net_uv.js:305:27)

Line 67:
eval(fs.readFileSync(path.join(LIBSPATH, "request.js"),
encoding="ascii")); 
```

**Comment by saghul** [comment]
I guess this no longer applies after the errno refactor. Closing.
