### ISSUE TITLE
unix: re-open tty stdio fds as /dev/tty?

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/libuv#601]
The basic logic is as follows, error handling elided for brevity:

``` c
for (fd = 0; fd <= 2; fd++) {
  if (isatty(fd))
    dup2(open("/dev/tty", O_RDWR), fd);
}
```

That lets libuv / node switch its tty to non-blocking mode without affecting other programs that expect it to be in blocking mode. That would, for example, fix the following issue:

```
$ node | cat
> process
[lots of data]
events.js:68
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: write EPIPE
    at errnoException (net.js:787:11)
    at Object.afterWrite (net.js:598:19)
    at process._makeCallback (node.js:248:20)
```

See joyent/node#3027 and [this comment](https://github.com/joyent/node/issues/3027#issuecomment-9722974) in particular.

It remains to be investigated if this approach works on all supported platforms.

**Comment by bnoordhuis** [comment]
Landed in 31f9fbc.
